/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/Charts/BaseChart.vue')['default']
    ChartDesigner: typeof import('./src/components/ChartDesigner/ChartDesigner.vue')['default']
    ChartRender: typeof import('./src/components/Charts/ChartRender.vue')['default']
    DatasetPane: typeof import('./src/components/Designer/PropsPane/DatasetPane.vue')['default']
    DropFieldItem: typeof import('./src/components/ChartDesigner/DropFieldItem.vue')['default']
    DropFields: typeof import('./src/components/ChartDesigner/DropFields.vue')['default']
    FieldPane: typeof import('./src/components/Designer/PropsPane/FieldPane.vue')['default']
    LayerItem: typeof import('./src/components/Designer/Layers/LayerItem.vue')['default']
    Layers: typeof import('./src/components/Designer/Layers/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    ManagementLayout: typeof import('./src/components/Layout/ManagementLayout.vue')['default']
    Menus: typeof import('./src/components/Designer/Menus/Menus.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    PagePane: typeof import('./src/components/Designer/PropsPane/PagePane.vue')['default']
    Pane: typeof import('./src/components/Designer/PropsPane/Pane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
  }
}
