/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartDesigner: typeof import('./src/components/ChartDesigner/ChartDesigner.vue')['default']
    DatasetPane: typeof import('./src/components/Designer/PropsPane/DatasetPane.vue')['default']
    FieldPane: typeof import('./src/components/Designer/PropsPane/FieldPane.vue')['default']
    LayerItem: typeof import('./src/components/Designer/Layers/LayerItem.vue')['default']
    Layers: typeof import('./src/components/Designer/Layers/index.vue')['default']
    ManagementLayout: typeof import('./src/components/Layout/ManagementLayout.vue')['default']
    Menus: typeof import('./src/components/Designer/Menus/Menus.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NUpload: typeof import('naive-ui')['NUpload']
    PagePane: typeof import('./src/components/Designer/PropsPane/PagePane.vue')['default']
    Pane: typeof import('./src/components/Designer/PropsPane/Pane.vue')['default']
    PaneContainer: typeof import('./src/components/Designer/PropsPane/PaneContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
